# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 106612fc2fc805cd5e33525155c8d70bc4a62073b304a5b6530847d239c9faffb58982fa4a49ca369cc8d547fe24e28a779a98ef0bd92caad0c19246b15bb5fd

test:
  secret_key_base: 408b15a7108f2792a21d46726af39aede53f0d0bebae81d48c5c62e02c9cf0f36e728df79ad7de7caa4120fc2580b45e54b817b30e0e8f8781ea7d0edfc96124

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
