# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82799c681536fe14bea6dc0ed5bdd42589b4e71733663d245bdad709a0eb6f95d2648a5db6364897f7650114359db5210701425c490a358301e4b93d95fb389b

test:
  secret_key_base: 057eedfbb504f471674bb4868bf0bc3f196f71043c2f5542adaab776bb799306aa83fa0fdc0b146dccefb52f4b0e48ea668a3651a3de7b24e7ae4f8841e1165d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
